### ISSUE TITLE
Coding session: Saturday, December 4, 2021

### ISSUE THREAD

**Issue by steffen** [rarely-org/rarely#9]
@PatrickHeneise is kindly [organizing](https://github.com/cyprusjs/CyprusJS/discussions/36) a coding session with the Cyprus JS community.

## Event details

https://www.linkedin.com/events/codeforagoodcausebycyprusjs6871136908521586688/about/
Everyone is welcome! ✨

In order to make the most out of the session, we can use this issue to map out an agenda and take notes as well as action items.

## Agenda (3 hours)

- Participant introductions (15 min)
- Context on what Rarely is (15 min)
- [Discuss backend stack](https://github.com/rarely-org/rarely/discussions/6)? (30 min)
- Explore 1-2 backend solutions? (2 hours)

**Comment by steffen** [comment]
👋 What are your thoughts on the agenda?

Looks like 9 attendees signed up so far.

Some additional thoughts:
- Should we do breakout rooms? (Not sure if Discord allows that.)
- Should we use [VS Code Live Share](https://code.visualstudio.com/learn/collaboration/live-share)?

**Comment by PatrickHeneise** [comment]
We can create several channels on Discord, let's see who's there and who wants to pair together. Yes on Live Share, I have good experience with that.

**Comment by steffen** [comment]
# Meeting minutes

## Date and time

Saturday, December 4, 2021, 2pm - 5pm OEZ

## Location

Discord server: CyprusJS

## Participants

- @PatrickHeneise
- @NVerban
- @saitonakamura
- @steffen

## Notes

- **Meeting room**
  - Discord audio and video worked well
  - Discord screen sharing was limited to a 720p resolution as we were using the free version which made text hard to read. Increasing the font size helped mostly
- **Development environment**
  - GitHub Codespaces worked mostly, some issues with accessing the app from Android
  - @saitonakamura ran the app from their local machine with the `--tunnel` option (which uses ngrok) and all participants were able to access the app from their devices and simulators
  - ❓ In theory when running the app in Codespaces and making the port public (or public within the org) users should also be able to access the app, though the manifest file still points bundle requests to localhost.
    - 🧪 Needs some investigation to see if there are options to make expo use the Codespaces URL as host
  - We tried out [Live Share](https://visualstudio.microsoft.com/de/services/live-share/) which worked nicely
    - Any participant was able to make a change in the file on the host who also ran the app and all were able to see the changes in their devices and simulators
    - @steffen was able to host a live share session from local VS Code, but was not able to join one. It worked via the VS Code web version though.
  - @saitonakamura pushed dependencies changes for the `--tunnel` option here: https://github.com/rarely-org/rarely/pull/10/commits/3b368c6e87ed9e8fc267c7ecaefa001e74e8fa40
- **Authentication**
  - User group will be mostly non-technical, mix of Android and iOS
  - We want to respect privacy as much as possible, ideally we don't need to save any personally identifiable information
  - 💡 Passwordless without any social provider might be a good option for a mobile app
    - ❓ We may not have to store the email, but only use it for sending the password as long as one remembers the username?
  - ❓ Do we want a dependency on a managed auth service and does it make it less accessible for outside contributors?
  - Generally speaking a managed auth service would move much of the responsibility and security of the authentication and user data to the managed service which might be good for an open source project
- **Managed services**
  - Managed services may not be very accessible for outside contributors
    - You can't just run it locally
    - You need access to the service, etc. AWS Cognito, Auth0
  - ❓ Services like https://planetscale.com/ could be run locally by just running MySQL locally or via Docker?
    - It would also be possible for contributors to just use a free developer account for the managed services, e.g. https://planetscale.com/pricing
  - https://supabase.com/ is open source and can be run locally it seems
- **Community project**
  - ❓ Who owns the code at the end if there will be money involved going forward (e.g. sponsors or NGO), could get tricky if there are open source contributions
- **Tech stack**
  - 💡 https://supabase.com/ looks like an interesting Firebase alternative

## Next steps

- Investigate authentication and backend tech stack in order to make a decision on it
- Continue to build out app scaffold in order to create specific issues that can be worked on in future coding sessions

**Comment by saitonakamura** [comment]
@steffen this summaries are awesome
